easzup: add chrony/haproxy images

diff --git a/tools/easzup b/tools/easzup
--- a/tools/easzup
+++ b/tools/easzup
@@ -30,12 +30,13 @@ function install_docker() {
     echo "[INFO] docker binaries already existed"
   else
     echo -e "[INFO] \033[33mdownloading docker binaries\033[0m $DOCKER_VER"
-    wget -c -P /etc/ansible/down "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
+    curl -C -O "$DOCKER_URL" || { echo "[ERROR] downloading docker failed"; exit 1; }
   fi
 
-  tar zxf /etc/ansible/down/docker-${DOCKER_VER}.tgz -C /etc/ansible/down
-  mv /etc/ansible/down/docker/* /opt/kube/bin
-  ln -sf /opt/kube/bin/docker /bin/docker
+  tar zxf ./docker-${DOCKER_VER}.tgz -C /etc/ansible/down && \
+  mv ./docker-${DOCKER_VER}.tgz /etc/ansible/down && \
+  mv /etc/ansible/down/docker/* /opt/kube/bin && \
+  ln -sf /opt/kube/bin/docker /bin/docker 
 
   echo "[INFO] generate docker service file"
   cat > /etc/systemd/system/docker.service << EOF
@@ -130,6 +131,7 @@ function get_ext_bin() {
 }
 
 function get_offline_image() {
+  # images needed by k8s cluster
   calicoVer=v3.4.4
   corednsVer=1.5.0
   dashboardVer=v1.10.1
@@ -138,6 +140,9 @@ function get_offline_image() {
   metricsVer=v0.3.2
   pauseVer=3.1
   traefikVer=v1.7.12
+  # images needed by systemd service
+  haproxyVer=1.9.8-alpine
+  chronyVer=0.1.0
 
   imageDir=/etc/ansible/down
   [[ -d "$imageDir" ]] || { echo "[ERROR] $imageDir not existed!"; exit 1; }
@@ -177,6 +182,14 @@ function get_offline_image() {
   if [[ ! -f "$imageDir/traefik_$traefikVer.tar" ]];then
     docker pull traefik:${traefikVer} && \
     docker save -o ${imageDir}/traefik_${traefikVer}.tar traefik:${traefikVer}
+  fi
+  if [[ ! -f "$imageDir/haproxy_$haproxyVer.tar" ]];then
+    docker pull haproxy:${haproxyVer} && \
+    docker save -o "$imageDir/haproxy_$haproxyVer.tar" haproxy:${haproxyVer}
+  fi
+  if [[ ! -f "$imageDir/chrony_$chronyVer.tar" ]];then
+    docker pull chrony:${chronyVer} && \
+    docker save -o "$imageDir/chrony_$chronyVer.tar" chrony:${chronyVer}
   fi
 }
 
